---
all:
  children:
    webservers:
      hosts:
        web01.dev.example.com:
          ansible_host: 10.0.0.11
        web02.dev.example.com:
          ansible_host: 10.0.0.12
    dbservers:
      hosts:
        db01.dev.example.com:
          ansible_host: 10.0.0.21
